### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by deliton** [deliton/idt#3]
- [ ] Implement Google Images Search Scraper

- [x] Implement Flickr Scraper

- [x] Implement DeviantArt Search

- [ ] Refactor code to better code standards (factories, constants, app states, etc) (PARTIALLY DONE)

- [ ] Fix bugs related to the amount of downloaded files being less than what was provided in the yaml file.

- [ ] Create a yaml parser outside main.py.

- [ ] Make the search engine factory instantiate the yaml parser and then select the according search engine

- [ ] Implement a way to generate a csv file for every dataset, containing its labels, amount of images in each class, image sources, score, etc.

- [ ] Implement a program that splits dataset's classes between TRAIN and VALID, asking for the user for the desired proportion

- [ ] Implement a program that executes common data augmentations/albumentaions in order to increase the size of the whole dataset.

- [ ] Implement a functional logger, that allows the user to debug and see what's happening with the scraping process.

- [ ] Consider the implementation of Selenium tools, in order to allow use of advanced scraping scripts and spiders. Keep in mind that it slows the process and require browser tools in order to run.
